### ISSUE TITLE
grad_norm: nan

### ISSUE THREAD

**Issue by missTL** [HXMap/MapQR#10]
![image](https://github.com/user-attachments/assets/43906a34-4dac-4e30-82f9-a8dcfc695fe7)
During training, grad_norm suddenly becomes nan

**Comment by fishmarch** [comment]
We also found this issue recently, but have not figured out where it comes from. It would happen one or two times during the whole training, thus we didn't notice before. We did some experiments and found it would appear when combing the preposed GKT-h and SGQ, although they both work well seperately.

**Comment by fishmarch** [comment]
Delete the following may solve this problem.
https://github.com/HXMap/MapQR/blob/7dc705740fe026b7908b10e60fcd2846f9bb83d9/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L149-L150
