### ISSUE TITLE
If "DetrTransformerDecoderLayer" has been used in mapqr, is the "self_attn_mask" for one2many strategy works in self attention module?

### ISSUE THREAD

**Issue by TommyAnqi** [HXMap/MapQR#12]

**Comment by fishmarch** [comment]
Thanks for pointing out this bug. I did not notice this before, I will further check and fix this recently.  The performance should be better after fixing this bug.

**Comment by fishmarch** [comment]
I upload a version to fix this bug. But I get similar perfomance with this attn_mask, it gets mAP1 = 42.9 and mAP2 = 66.6.
