### ISSUE TITLE
A small confuse about paper

### ISSUE THREAD

**Issue by qianbanxuezhiqian** [HXMap/MapQR#14]
Hi, I have a small confuse about the SGQ decoder, what's the difference between SGQ with MapTRv2's query mechanism, seems they all use instance query instead of point query as the q value, but SGQ uses query embedding with ref points to encoding position info as MapTRv2 uses pos_query? 
Am i missed some thing?
Wish for your reply

**Comment by fishmarch** [comment]
Hi! Actually, MapTRv2 is using point query, which is initilized from instance part and point part (pos_query). Thus, MapTRv2 predicts a point position from each point query. In our MapQR, we generate point queries from instance query (scattering), and gather them back to instance query, then each instance query predicts 20 point positions. It will be more clear from the codes.

**Comment by qianbanxuezhiqian** [comment]
Thanks for your reply, I found it in the code and it solves my confuse!
