### ISSUE TITLE
when will you release the code?

### ISSUE THREAD

**Issue by Ming109** [HXMap/MapQR#2]
Your work is very innovative. May I ask when you can upload the code?

**Comment by fishmarch** [comment]
Thanks. We are preparing the codes and may release this month.

**Comment by Ming109** [comment]
I'm looking forward to it.



---- Replied Message ----
| From | Xiaoyu ***@***.***> |
| Date | 03/14/2024 15:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HXMap/MapQR] when will you release the code? (Issue #2) |

Thanks. We are preparing the codes and may release this month.

**Comment by fishmarch** [comment]
We have released codes.

**Comment by Ming109** [comment]
thanks a lot



---- Replied Message ----
| From | Xiaoyu ***@***.***> |
| Date | 03/19/2024 11:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HXMap/MapQR] when will you release the code? (Issue #2) |

We have released codes.
