### ISSUE TITLE
queue_length is 1

### ISSUE THREAD

**Issue by canteen-man** [HXMap/MapQR#5]
你好
MapTR和MapTR-V2的queue_lenght都是1，MapQR的config里也是1，所以MapQR也没有实际应用CAN吗
谢谢

**Comment by fishmarch** [comment]
Yes, as MapTR, we do not utilise temporal information in MapQR for this version. But,  can_bus signals are fused into bev queries  , copied from BEVFormer, although I think can_bus contributes little here.

**Comment by canteen-man** [comment]
你好，感谢你的回复
是因为bevformer用hybrid 2d的temporal self attention在实际对比试验里没有太大提升，所以就都没有用hybrid 2d的TSA去训练吗。
MapTR和MapTR-V2论文里的指标也都是没有用上hybrid 2d的TSA。
谢谢

**Comment by fishmarch** [comment]
Actually, I remember we get some improvements when using temporal self attention, but we do not add this temporal information to keep consistent with MapTR.

**Comment by canteen-man** [comment]
谢谢
感谢你的帮助
