### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by missTL** [HXMap/MapQR#8]
![image](https://github.com/user-attachments/assets/7f028920-ccfb-4903-92bd-fd5f3362c67d)
May I ask if you can provide logs for this configuration? I need to compare the intermediate results

**Comment by fishmarch** [comment]
We didn't save those logs. But luckily, I find a log of the recent testing and it gets similar results. You may refer to it.
[mapqr.log](https://github.com/user-attachments/files/16425516/mapqr.log)

**Comment by missTL** [comment]
thanks
