### ISSUE TITLE
Question about lane smoothness

### ISSUE THREAD

**Issue by ellen19967** [HXMap/MapQR#9]
Thanks for the good job! Have you ever encountered a situation where the predicted map elements have poor smoothness, and is there any solution to this problem?

**Comment by fishmarch** [comment]
It may happen because the prediction is not forced to be smooth. I think this problem may be refined if using the different processing of pedestrian_crossings groundtruth like in StreamMapNet.

**Comment by ellen19967** [comment]
Thanks a lot!
